//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContosoSite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContosoSite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaren
        ///Aarika
        ///Abagael
        ///Abagail
        ///Abbe
        ///Abbey
        ///Abbi
        ///Abbie
        ///Abby
        ///Abbye
        ///Abigael
        ///Abigail
        ///Abigale
        ///Abra
        ///Ada
        ///Adah
        ///Adaline
        ///Adan
        ///Adara
        ///Adda
        ///Addi
        ///Addia
        ///Addie
        ///Addy
        ///Adel
        ///Adela
        ///Adelaida
        ///Adelaide
        ///Adele
        ///Adelheid
        ///Adelice
        ///Adelina
        ///Adelind
        ///Adeline
        ///Adella
        ///Adelle
        ///Adena
        ///Adey
        ///Adi
        ///Adiana
        ///Adina
        ///Adora
        ///Adore
        ///Adoree
        ///Adorne
        ///Adrea
        ///Adria
        ///Adriaens
        ///Adrian
        ///Adriana
        ///Adriane
        ///Adrianna
        ///Adrianne
        ///Adriena
        ///Adrienne
        ///Aeriel
        ///Aeriela
        ///Aeriell
        ///Afton
        ///Ag
        ///Agace
        ///Agata
        ///Agatha
        ///Agathe
        ///Aggi
        ///Aggie
        ///Aggy
        ///Ag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string first_names {
            get {
                return ResourceManager.GetString("first_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AARON
        ///ABBOTT
        ///ABEL
        ///ABELL
        ///ABERNATHY
        ///ABNER
        ///ABNEY
        ///ABRAHAM
        ///ABRAMS
        ///ABREU
        ///ACEVEDO
        ///ACKER
        ///ACKERMAN
        ///ACKLEY
        ///ACOSTA
        ///ACUNA
        ///ADAIR
        ///ADAM
        ///ADAME
        ///ADAMS
        ///ADAMSON
        ///ADCOCK
        ///ADDISON
        ///ADKINS
        ///ADLER
        ///AGEE
        ///AGNEW
        ///AGUAYO
        ///AGUIAR
        ///AGUILAR
        ///AGUILERA
        ///AGUIRRE
        ///AHERN
        ///AHMAD
        ///AHMED
        ///AHRENS
        ///AIELLO
        ///AIKEN
        ///AINSWORTH
        ///AKERS
        ///AKIN
        ///AKINS
        ///ALANIZ
        ///ALARCON
        ///ALBA
        ///ALBERS
        ///ALBERT
        ///ALBERTSON
        ///ALBRECHT
        ///ALBRIGHT
        ///ALCALA
        ///ALCORN
        ///ALDERMAN
        ///ALDRICH
        ///ALDRIDGE
        ///ALEMAN
        ///ALEXANDER
        ///ALFARO
        ///ALFONSO
        ///ALFORD
        ///ALFRED
        ///ALGER
        ///ALI
        ///ALICEA
        ///ALLAN
        ///ALLARD
        ///ALLEN
        ///ALLEY
        ///ALLISON
        ///ALLMAN
        ///ALLRED
        ///ALMANZA
        ///ALMEIDA
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string last_names {
            get {
                return ResourceManager.GetString("last_names", resourceCulture);
            }
        }
    }
}
